version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3000:4010"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.production
    command: npm run start
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rizal
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
