version: '3.8'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    command: npm run start:dev
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rizal
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
