version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
  
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    command: npm run start:dev
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rizal
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
