version: '3.8'
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3000:4010"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.production
    command: npm run start